search_task:
  description: >-
    Search for new {technology} energy projects in {country} from the last 6 months.
    Focus on project sizes, locations, developers, and investment values.
    Focus on all new projects that are not yet constructed.
    Use SerperDev to find relevant news articles and project announcements.
  expected_output: >-
    A list of URLs and brief descriptions of relevant {country} {technology} project announcements
  agent: web_researcher

scraping_task:
  description: >-
    Scrape detailed information from the provided URLs about {country} {technology} projects.
    Extract project details including:
    - Project name and location
    - Capacity (MW)
    - Developer/Company
    - Timeline
    - Current status
  expected_output: >-
    Structured data from each website in JSON format containing all available project details
  agent: web_scraper

analysis_task:
  description: |
    Analyze the scraped data about {country} {technology} projects and create a standardized JSON summary.
    The output must follow this exact structure:
    {{
      "Summary": {{
        "Major developers active in the market": ["<string>"],
        "Most promising projects":
      - "<string: Project name> - <Why it's promising; why foreign EPCs/investors should consider it>"
      - "<string: Project name> - <Why it's promising; why foreign EPCs/investors should consider it>"
      - "<string: Project name> - <Why it's promising; why foreign EPCs/investors should consider it>"
      }},
      "Detailed Project List": [
        {{
          "ProjectName": "<string>",
          "Location": "<string>",
          "Capacity_MW": <number>,
          "Developer": "<string>",
          "Timeline": "<string>",
          "CurrentStatus": "<string>",
          "source_url": "<string>",
          "source_name": "<string>",
          "category": "<string: development | investment | planning>",
          "Date": "<string: MM/DD/YYYY>",
          "KeyPoints": [
            "<string: point highlighting technical opportunity>",
            "<string: point highlighting procurement opportunity>",
            "<string: point highlighting timeline consideration>",
            "<string: point highlighting competitive advantage potential>",
            "<string: point highlighting regulatory consideration>",
            "<string: point highlighting financial consideration>"
          ],
          "partners": ["<string: Partner 1>", "<string: Partner 2>"]
        }}
      ]
    }}
    Ensure all numeric values are properly formatted and all fields are present.
  expected_output: >-
    A JSON document with standardized Summary and Detailed Project List sections
  agent: data_analyst
